#!/usr/bin/env bash
# Check if an IP address has been passed as an argument

# Get the script name without the path
SCRIPT_NAME=$(basename "$0")

if [ "$#" -ne 1 ]; then
    echo "Usage: $SCRIPT_NAME {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS=$1

ping -c 5 "$IP_ADDRESS"