#!/usr/bin/env bash
# Set localhost to resolve to 127.0.0.2 and
# facebook.com to 8.8.8.8 on an Ubuntu server

sudo cp /etc/hosts /etc/hosts.backup

if grep -q "127.0.0.1 localhost" /etc/hosts; then
    sudo sed -i '/localhost/c\127.0.0.2 localhost' /etc/hosts
else
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
fi

if grep -q "facebook.com" /etc/hosts; then
    sudo sed -i '/facebook.com/c\8.8.8.8 facebook.com' /etc/hosts
else 
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
fi
